services:
  - type: web
    name: cuidabem
    env: python
    plan: starter
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --preload -w 2 -b 0.0.0.0:$PORT app:app
    disk:
      name: db
      sizeGB: 1
      mountPath: /var/data
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_PATH
        value: /var/data/cuidabem.db